name: Send message to Matrix
description: Action that sends a message log of the action to a Matrix room

inputs:
  token:
    description: Token of your account
  room_id:
    description: Room ID where you want to post the comment
  base_url:
    description: Base URL
    default: "https://matrix-client.matrix.org"
  message:
    description: Message that you want to send
    default: "Ejecutado el workflow <b>${{ github.workflow }}</b> mediante <b>${{ github.event_name }}</b>"

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        url="${{ inputs.base_url }}/_matrix/client/r0/rooms/${{ inputs.room_id }}/send/m.room.message"

        headers="Authorization: Bearer ${{ inputs.token }}"
        data=$(cat <<EOF
        {
            "body": "${{ inputs.message }}",
            "format": "org.matrix.custom.html",
            "formatted_body": "${{ inputs.message }}",
            "msgtype": "m.text"
        }
        EOF
        )

        curl -X POST \
          "$url" \
          -H "$headers" \
          -H "Content-Type: application/json" \
          -d "$data"
